spring:
  application:
    name: mybatisdemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: lucene
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lucene?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/templates/,classpath:/static/,classpath:/public/,file:${web.upload-path}
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
mybatis:
  type-aliases-package: com.example.mybatisdemo.eneities
  mapper-locations: classpath:/resources/Mybatis/mapper/*.xml

server:
  port: 8088

